easy_admin:
  design:
    assets:
      css:
        - '/assets/bs-tags/bootstrap-tagsinput.css'
      js:
        - '/assets/bs-tags/bootstrap-tagsinput.js'
    menu:
      - {label: "Entities"}
      - label: "Posts"
        children:
          - {entity: Post, label: "Posts list", icon: "th-list"}
          - {entity: Post, label: "Add post", icon: "plus", params: {action: 'new'}}
      - label: "Category"
        children:
          - {entity: Category, label: "List all categories", icon: "th-list"}
          - {entity: Category, label: "Add category", icon: "plus"}
      - Tag
      - {label: "Settings"}
      - {entity: User, icon: "user"}
  site_name: '<b>Skud</b>'
  user:
    display_name: true
    display_avatar: true
    name_property_path: 'fullName'
  entities:
    Post:
      class: App\Entity\Post
      label: "Post"
      form:
        fields:
            - {type: 'group', icon: 'pencil', label: 'Basic Information', css_class: 'col-lg-7'}
            - title
            - {property: 'content' , type: 'textarea'}
            - createdAt
            - published
            - {type: 'group', icon: 'th-list', label: 'Other Information', css_class: 'col-lg-5'}
            - category
            - { property: 'tags', type: 'App\Form\TagType', type_options: {attr: {data-role: 'tagsinput'}}}
            - {type: 'group', icon: 'clip', label: 'Attachments', css_class: 'col-lg-5'}
            - { property: 'thumbnailFile', type: 'vich_image' }
            - { property: 'attachments', type: 'collection', type_options: {entry_type: 'App\Form\AttachmentType', by_reference: false} }
      list:
        collapse_actions: true
        actions: ['show', 'edit', 'delete']
        batch_actions: ['delete']
        title: "Some posts from the other world"
        fields: ['title', 'content', 'createdAt', {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}]
        filters: ['published','tags','category']
      show:
        fields:
          - title
          - {property: 'content', type: 'raw'}
          - createdAt
          - published
          - {property: 'thumbnail', type: 'image', base_path: '%uploads_path%'}
          - {property: 'attachments', template: 'images.html.twig' }
          - tags
      edit:
        help: "Hello there"

    Category:
      class: App\Entity\Category
      new:
        fields:
          - title
          - slug
    Tag:
      class: App\Entity\Tag
      form:
        fields:
          - name
          - slug
    User:
            class: App\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }    